// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMinyunAreaChargeIdPrefix = "cache:minyun:areaCharge:id:"
)

type (
	areaChargeModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *AreaCharge) error

		FindOne(ctx context.Context, id int64) (*AreaCharge, error)
		Update(ctx context.Context, tx *gorm.DB, data *AreaCharge) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultAreaChargeModel struct {
		gormc.CachedConn
		table string
	}

	AreaCharge struct {
		Id          int64          `gorm:"column:id"`
		AreaName    string         `gorm:"column:area_name"` // 区域名称
		Remark      string         `gorm:"column:remark"`
		ComboId     int64          `gorm:"column:combo_id"`      // 余额充电收费模板id
		TempComboId int64          `gorm:"column:temp_combo_id"` // 临时充电收费模板
		AreaType    int64          `gorm:"column:area_type"`     // 区域类型
		CreatedAt   time.Time      `gorm:"column:created_at"`
		UpdatedAt   time.Time      `gorm:"column:updated_at"`
		DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;index"`
		SiteId      int64          `gorm:"column:site_id"`
	}
)

func (AreaCharge) TableName() string {
	return "`area_charge`"
}

func newAreaChargeModel(conn *gorm.DB, c cache.CacheConf) *defaultAreaChargeModel {
	return &defaultAreaChargeModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`area_charge`",
	}
}

func (m *defaultAreaChargeModel) Insert(ctx context.Context, tx *gorm.DB, data *AreaCharge) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultAreaChargeModel) FindOne(ctx context.Context, id int64) (*AreaCharge, error) {
	minyunAreaChargeIdKey := fmt.Sprintf("%s%v", cacheMinyunAreaChargeIdPrefix, id)
	var resp AreaCharge
	err := m.QueryCtx(ctx, &resp, minyunAreaChargeIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&AreaCharge{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAreaChargeModel) Update(ctx context.Context, tx *gorm.DB, data *AreaCharge) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultAreaChargeModel) getCacheKeys(data *AreaCharge) []string {
	if data == nil {
		return []string{}
	}
	minyunAreaChargeIdKey := fmt.Sprintf("%s%v", cacheMinyunAreaChargeIdPrefix, data.Id)
	cacheKeys := []string{
		minyunAreaChargeIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultAreaChargeModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&AreaCharge{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultAreaChargeModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultAreaChargeModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMinyunAreaChargeIdPrefix, primary)
}

func (m *defaultAreaChargeModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&AreaCharge{}).Where("`id` = ?", primary).Take(v).Error
}
