// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMinyunLogOnlineCardIdPrefix = "cache:minyun:logOnlineCard:id:"
)

type (
	logOnlineCardModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *LogOnlineCard) error

		FindOne(ctx context.Context, id int64) (*LogOnlineCard, error)
		Update(ctx context.Context, tx *gorm.DB, data *LogOnlineCard) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultLogOnlineCardModel struct {
		gormc.CachedConn
		table string
	}

	LogOnlineCard struct {
		Id          int64          `gorm:"column:id"`
		CardId      int64          `gorm:"column:card_id"`
		Symbol      int64          `gorm:"column:symbol"`       // 操作类型：1，增加，2减少
		ValueLog    string         `gorm:"column:value_log"`    // 增加或减少的值，电量为Decem，所以取值要根据需要转化
		TriggerTime int64          `gorm:"column:trigger_time"` // 触发时间
		TrigerType  int64          `gorm:"column:triger_type"`  // 1,充值，2，退款，3，后台修改
		OperatId    int64          `gorm:"column:operat_id"`    // 操作者id：0为用户 非0则为系统管理员操作
		CreatedAt   time.Time      `gorm:"column:created_at"`
		UpdatedAt   time.Time      `gorm:"column:updated_at"`
		DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;index"`
		UpingValue  string         `gorm:"column:uping_value"` // 操作前账户剩余资源
		Remark      string         `gorm:"column:remark"`
	}
)

func (LogOnlineCard) TableName() string {
	return "`log_online_card`"
}

func newLogOnlineCardModel(conn *gorm.DB, c cache.CacheConf) *defaultLogOnlineCardModel {
	return &defaultLogOnlineCardModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`log_online_card`",
	}
}

func (m *defaultLogOnlineCardModel) Insert(ctx context.Context, tx *gorm.DB, data *LogOnlineCard) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLogOnlineCardModel) FindOne(ctx context.Context, id int64) (*LogOnlineCard, error) {
	minyunLogOnlineCardIdKey := fmt.Sprintf("%s%v", cacheMinyunLogOnlineCardIdPrefix, id)
	var resp LogOnlineCard
	err := m.QueryCtx(ctx, &resp, minyunLogOnlineCardIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&LogOnlineCard{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLogOnlineCardModel) Update(ctx context.Context, tx *gorm.DB, data *LogOnlineCard) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultLogOnlineCardModel) getCacheKeys(data *LogOnlineCard) []string {
	if data == nil {
		return []string{}
	}
	minyunLogOnlineCardIdKey := fmt.Sprintf("%s%v", cacheMinyunLogOnlineCardIdPrefix, data.Id)
	cacheKeys := []string{
		minyunLogOnlineCardIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultLogOnlineCardModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&LogOnlineCard{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLogOnlineCardModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultLogOnlineCardModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMinyunLogOnlineCardIdPrefix, primary)
}

func (m *defaultLogOnlineCardModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&LogOnlineCard{}).Where("`id` = ?", primary).Take(v).Error
}
