// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMinyunLogUserShopIdPrefix = "cache:minyun:logUserShop:id:"
)

type (
	logUserShopModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *LogUserShop) error

		FindOne(ctx context.Context, id int64) (*LogUserShop, error)
		Update(ctx context.Context, tx *gorm.DB, data *LogUserShop) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultLogUserShopModel struct {
		gormc.CachedConn
		table string
	}

	LogUserShop struct {
		Id          int64          `gorm:"column:id"`
		UserShopId  int64          `gorm:"column:user_shop_id"` // user_shop外键，记录商户用户的流水日志
		LogType     int64          `gorm:"column:log_type"`     // 1,订单收入2，订单退款3，账户提现4，手续费扣除5，服务购买
		LogValue    int64          `gorm:"column:log_value"`    // 单位 分
		LogName     string         `gorm:"column:log_name"`     // 操作项目名称，如 充电订单收入等
		Symbol      int64          `gorm:"column:symbol"`       // 操作类型：1，增加，2减少
		TriggerTime int64          `gorm:"column:trigger_time"` // 触发时间
		OperatId    int64          `gorm:"column:operat_id"`    // 操作者id：0为系统自动 非0则为操作人的id
		CreatedAt   time.Time      `gorm:"column:created_at"`
		UpdatedAt   time.Time      `gorm:"column:updated_at"`
		DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;index"`
		UpingValue  string         `gorm:"column:uping_value"` // 操作前账户剩余资源
		Remark      string         `gorm:"column:remark"`
		SiteId      int64          `gorm:"column:site_id"`
		OrderId     string         `gorm:"column:order_id"` // 提现id
		OutNo       string         `gorm:"column:out_no"`   // 外部id
	}
)

func (LogUserShop) TableName() string {
	return "`log_user_shop`"
}

func newLogUserShopModel(conn *gorm.DB, c cache.CacheConf) *defaultLogUserShopModel {
	return &defaultLogUserShopModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`log_user_shop`",
	}
}

func (m *defaultLogUserShopModel) Insert(ctx context.Context, tx *gorm.DB, data *LogUserShop) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLogUserShopModel) FindOne(ctx context.Context, id int64) (*LogUserShop, error) {
	minyunLogUserShopIdKey := fmt.Sprintf("%s%v", cacheMinyunLogUserShopIdPrefix, id)
	var resp LogUserShop
	err := m.QueryCtx(ctx, &resp, minyunLogUserShopIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&LogUserShop{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLogUserShopModel) Update(ctx context.Context, tx *gorm.DB, data *LogUserShop) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultLogUserShopModel) getCacheKeys(data *LogUserShop) []string {
	if data == nil {
		return []string{}
	}
	minyunLogUserShopIdKey := fmt.Sprintf("%s%v", cacheMinyunLogUserShopIdPrefix, data.Id)
	cacheKeys := []string{
		minyunLogUserShopIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultLogUserShopModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&LogUserShop{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLogUserShopModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultLogUserShopModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMinyunLogUserShopIdPrefix, primary)
}

func (m *defaultLogUserShopModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&LogUserShop{}).Where("`id` = ?", primary).Take(v).Error
}
