// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMinyunLogUserBasicIdPrefix = "cache:minyun:logUserBasic:id:"
)

type (
	logUserBasicModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *LogUserBasic) error

		FindOne(ctx context.Context, id int64) (*LogUserBasic, error)
		Update(ctx context.Context, tx *gorm.DB, data *LogUserBasic) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultLogUserBasicModel struct {
		gormc.CachedConn
		table string
	}

	LogUserBasic struct {
		Id          int64          `gorm:"column:id"`
		UserId      int64          `gorm:"column:user_id"`
		LogType     int64          `gorm:"column:log_type"`     // 1，余额 2，积分，3，碳积分
		LogValue    int64          `gorm:"column:log_value"`    // 单位 分
		LogName     string         `gorm:"column:log_name"`     // 操作项目名称，如余额，积分等收入或支出
		Symbol      int64          `gorm:"column:symbol"`       // 操作类型：1，增加，2减少
		TriggerTime int64          `gorm:"column:trigger_time"` // 触发时间
		OperatId    int64          `gorm:"column:operat_id"`    // 操作者id：0为系统自动 非0则为操作人的id
		CreatedAt   time.Time      `gorm:"column:created_at"`
		UpdatedAt   time.Time      `gorm:"column:updated_at"`
		DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;index"`
		UpingValue  string         `gorm:"column:uping_value"` // 操作前账户剩余资源
		Remark      string         `gorm:"column:remark"`
		SiteId      int64          `gorm:"column:site_id"`
		OrderId     string         `gorm:"column:order_id"` // 充值id
		OutNo       string         `gorm:"column:out_no"`   // 外部id
	}
)

func (LogUserBasic) TableName() string {
	return "`log_user_basic`"
}

func newLogUserBasicModel(conn *gorm.DB, c cache.CacheConf) *defaultLogUserBasicModel {
	return &defaultLogUserBasicModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`log_user_basic`",
	}
}

func (m *defaultLogUserBasicModel) Insert(ctx context.Context, tx *gorm.DB, data *LogUserBasic) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLogUserBasicModel) FindOne(ctx context.Context, id int64) (*LogUserBasic, error) {
	minyunLogUserBasicIdKey := fmt.Sprintf("%s%v", cacheMinyunLogUserBasicIdPrefix, id)
	var resp LogUserBasic
	err := m.QueryCtx(ctx, &resp, minyunLogUserBasicIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&LogUserBasic{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLogUserBasicModel) Update(ctx context.Context, tx *gorm.DB, data *LogUserBasic) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultLogUserBasicModel) getCacheKeys(data *LogUserBasic) []string {
	if data == nil {
		return []string{}
	}
	minyunLogUserBasicIdKey := fmt.Sprintf("%s%v", cacheMinyunLogUserBasicIdPrefix, data.Id)
	cacheKeys := []string{
		minyunLogUserBasicIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultLogUserBasicModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&LogUserBasic{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLogUserBasicModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultLogUserBasicModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMinyunLogUserBasicIdPrefix, primary)
}

func (m *defaultLogUserBasicModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&LogUserBasic{}).Where("`id` = ?", primary).Take(v).Error
}
