// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMinyunScaleUserShopIdPrefix = "cache:minyun:scaleUserShop:id:"
)

type (
	scaleUserShopModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *ScaleUserShop) error

		FindOne(ctx context.Context, id int64) (*ScaleUserShop, error)
		Update(ctx context.Context, tx *gorm.DB, data *ScaleUserShop) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultScaleUserShopModel struct {
		gormc.CachedConn
		table string
	}

	ScaleUserShop struct {
		Id         int64          `gorm:"column:id"`
		UserId     int64          `gorm:"column:user_id"`
		UserShopId int64          `gorm:"column:user_shop_id"`
		SiteId     int64          `gorm:"column:site_id"`
		Scale      int64          `gorm:"column:scale"` // 分润比例 单位百分1
		PlatId     int64          `gorm:"column:plat_id"`
		ChannelId  int64          `gorm:"column:channel_id"`
		ShopId     int64          `gorm:"column:shop_id"`
		CreatedAt  time.Time      `gorm:"column:created_at"`
		UpdatedAt  time.Time      `gorm:"column:updated_at"`
		DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;index"`
		Remark     string         `gorm:"column:remark"`
	}
)

func (ScaleUserShop) TableName() string {
	return "`scale_user_shop`"
}

func newScaleUserShopModel(conn *gorm.DB, c cache.CacheConf) *defaultScaleUserShopModel {
	return &defaultScaleUserShopModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`scale_user_shop`",
	}
}

func (m *defaultScaleUserShopModel) Insert(ctx context.Context, tx *gorm.DB, data *ScaleUserShop) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultScaleUserShopModel) FindOne(ctx context.Context, id int64) (*ScaleUserShop, error) {
	minyunScaleUserShopIdKey := fmt.Sprintf("%s%v", cacheMinyunScaleUserShopIdPrefix, id)
	var resp ScaleUserShop
	err := m.QueryCtx(ctx, &resp, minyunScaleUserShopIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&ScaleUserShop{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScaleUserShopModel) Update(ctx context.Context, tx *gorm.DB, data *ScaleUserShop) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultScaleUserShopModel) getCacheKeys(data *ScaleUserShop) []string {
	if data == nil {
		return []string{}
	}
	minyunScaleUserShopIdKey := fmt.Sprintf("%s%v", cacheMinyunScaleUserShopIdPrefix, data.Id)
	cacheKeys := []string{
		minyunScaleUserShopIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultScaleUserShopModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&ScaleUserShop{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultScaleUserShopModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultScaleUserShopModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMinyunScaleUserShopIdPrefix, primary)
}

func (m *defaultScaleUserShopModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&ScaleUserShop{}).Where("`id` = ?", primary).Take(v).Error
}
