// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMinyunUserOfflineCardIdPrefix = "cache:minyun:userOfflineCard:id:"
)

type (
	userOfflineCardModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *UserOfflineCard) error

		FindOne(ctx context.Context, id int64) (*UserOfflineCard, error)
		Update(ctx context.Context, tx *gorm.DB, data *UserOfflineCard) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultUserOfflineCardModel struct {
		gormc.CachedConn
		table string
	}

	UserOfflineCard struct {
		Id           int64          `gorm:"column:id"`
		OfflineCardId string         `gorm:"column:offline_card_id"` // 线下卡id 实际卡内id
		UserId       int64          `gorm:"column:user_id"`
		CreatedAt    time.Time      `gorm:"column:created_at"`
		UpdatedAt    time.Time      `gorm:"column:updated_at"`
		DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;index"`
		Remark       string         `gorm:"column:remark"`
	}
)

func (UserOfflineCard) TableName() string {
	return "`user_offline_card`"
}

func newUserOfflineCardModel(conn *gorm.DB, c cache.CacheConf) *defaultUserOfflineCardModel {
	return &defaultUserOfflineCardModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`user_offline_card`",
	}
}

func (m *defaultUserOfflineCardModel) Insert(ctx context.Context, tx *gorm.DB, data *UserOfflineCard) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUserOfflineCardModel) FindOne(ctx context.Context, id int64) (*UserOfflineCard, error) {
	minyunUserOfflineCardIdKey := fmt.Sprintf("%s%v", cacheMinyunUserOfflineCardIdPrefix, id)
	var resp UserOfflineCard
	err := m.QueryCtx(ctx, &resp, minyunUserOfflineCardIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&UserOfflineCard{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserOfflineCardModel) Update(ctx context.Context, tx *gorm.DB, data *UserOfflineCard) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultUserOfflineCardModel) getCacheKeys(data *UserOfflineCard) []string {
	if data == nil {
		return []string{}
	}
	minyunUserOfflineCardIdKey := fmt.Sprintf("%s%v", cacheMinyunUserOfflineCardIdPrefix, data.Id)
	cacheKeys := []string{
		minyunUserOfflineCardIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultUserOfflineCardModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&UserOfflineCard{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultUserOfflineCardModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultUserOfflineCardModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMinyunUserOfflineCardIdPrefix, primary)
}

func (m *defaultUserOfflineCardModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&UserOfflineCard{}).Where("`id` = ?", primary).Take(v).Error
}
